### ISSUE TITLE
Tests are failing

### ISSUE THREAD

**Issue by mseri** [ygrek/ocaml-libevent#1] opened 2019-03-22 14:24 UTC
See: https://travis-ci.org/ocaml/opam-repository/builds/509893439

**Comment by rr0gi** [comment] 2024-04-09 19:40
link is 404 now (5 years passed :penguin:) and cannot reproduce, so closing
I still have some suspicion there is bug lurking in tests/bindings, should open new issue when have more info

**Comment by ygrek** [comment] 2024-04-09 19:41
link is 404 now (5 years passed 🐧) and cannot reproduce, so closing
I still have some suspicion there is bug lurking in tests/bindings, should open new issue when have more info

**Closed as completed by ygrek** 2024-04-09 19:41 UTC
